### PR TITLE
HashEntry updates

### PR DESCRIPTION
**Pull request by setrofim**
- Change the separator in string representation to "';" to be consistent with RFC6920
- Add a couple of utility functions to help creating HashEntries from strings.

### CODE REVIEW

**Comment by setrofim** [comment]
Not really. The background for this is that I'm implementing `CryptoKey` for `corim`. A digest being one of the key types. `corim` already uses `swid.HashEntry` for digests elsewhere. The CORIM spec has its own definition of digest (distinct but largely isomorphic to `swid.HashEntry`). That defintion references this: https://www.iana.org/assignments/named-information/named-information.xhtml, which intern ferfs to RFC6920.  While the RFC is not directly related to what `corim` is doing, it does define a string representation for hashes, and it seems crazy to deviate from it for no apparent reason (I was unable to identify the source of the ":" as the separtor).

This won't really help with the issue you've listed since the SWID XML tags encode things differently:
- They appear to use hex encoding rather than base64
-  they do not include the algorithm in the hash value, but instead it is in the attribute name (which only works in XML), e.g.

```
SHA256:​
hash​
=​
”a314fc2dc663ae7a6b6bc6787594057396e6b3f569cd50fd5ddb4d1bbafd2b6a”
```
So the value extracted form XML cannot be used with `swid.HashValue` directly, you'd have to convert, using parsing the attribute tag Oor something similar).

The other enhancements  in this pull is also to help with use for CryptoKey.

**Comment by thomas-fossati** [comment]
> [...] That defintion references this: https://www.iana.org/assignments/named-information/named-information.xhtml, which intern ferfs to RFC6920. While the RFC is not directly related to what `corim` is doing, it does define a string representation for hashes, and it seems crazy to deviate from it for no apparent reason (I was unable to identify the source of the ":" as the separtor).

Hmm, 6920 defines a whole new URI scheme, I don't think its `alg-sepval` is supposed to be used as a top-level production.

Besides, if we change this we'd also need to change all the templates that are using this serialisation convention.

**Comment by setrofim** [comment]
> I don't think its alg-sepval is supposed to be used as a top-level production.

Why not? Given that this already exists, IMO, we need a good reason to deviate form it, rather than follow it. Basically, I haven't found a good reason why colon was used in favour of any other non-base64 symbol (if there is one, please point me to it). Conversely, RFC6020 gives a good reason to use semicolon, even if the RFC is not directly applicable. All the more so since it's  indrectly referenced in the CORIM spec (via the IANA table).

> Besides, if we change this we'd also need to change all the templates that are using this serialisation convention.

Better now than later. Besides, are there _that_ many templats with hard-coded hashes? The longer we leave it, the more the convention becomes established, and the more difficult it will be to bring in line with previously established conventions in other areas.

**Comment by thomas-fossati** [comment]
> > I don't think its alg-sepval is supposed to be used as a top-level production.
> 
> Why not?

OK, reading [Section 5](https://www.rfc-editor.org/rfc/rfc6920.html#section-5)  I think I see the light.  `alg-val` (the "URL segment form") effectively looks like it's intended as a generic, reusable component.

> > Besides, if we change this we'd also need to change all the templates that are using this serialisation convention.
> 
> Better now than later. Besides, are there _that_ many templats with hard-coded hashes?

We don't know for sure.  veraison/swid has a few [dependent packages](https://github.com/veraison/swid/network/dependents).
And, as far as I know, we likely have a few private projects using it too.

So it seems we'd be potentially disrupting a non-negligible user base.

**Comment by setrofim** [comment]
> We don't know for sure. veraison/swid has a few [dependent packages](https://github.com/veraison/swid/network/dependents).

I mean, most of those are forks or our own projects, but....

> So it seems we'd be potentially disrupting a non-negligible user base.

Sure, I understand this change is potentially disruptive. But that's only going to get worse going forward. It is better to cause the disruption now that to further propagate the idiosynchratic format.

The required migration is straight-forward enough that we can provide a script to automatically update templates if there is a need.

FWIW the crypto keys changes to `corim` to bring it in line with the spec are already going to potentially require template updates (the "verif keys" currently on `main` are completely different). And there will be even greater disruptions down the line as the lib is brought into closer aligment with the rest of the spec as it progresses.

**Comment by thomas-fossati** [comment]
JSON templates are external interface so this change is likely to deserve a version bump.

Since, as you note above, we have a bunch of substantial changes ahead in `veraison/corim` (included changing the processing model based on profile selection), I am wondering whether we can delay this change and package it into a `veraison/corim/v2` story?

(Besides, we probably want to start explicitly versioning the templates as well.)

**Comment by setrofim** [comment]
The point is that there will be a continuing stream of breaking changes over the coming months. There is no point in delaying. And I this case, the point is to force the migration early rather than allowing to proliferate.

I'm fine with tagging and doing a lib release off `main` before this is merged (ditto for equivalent changes on `corim`). However, given that the spec is in draft, there is no point in maintaining stability in lib interface if it means it will grow increasingly stale. I don't think we're at the stage of even considering /v2 - - too far into the future. We should not allow this to fester foe months. And the crypto key changes will improve robustness of generated corims, and relying services, making things easier in the mean time. As those are already gonna break templates, additional disruption from this is marginal. 

Besides, dependants are pinned to a particular tag/commit so it's not like they suddenly gonna break when this is merged - - they can choose when they want to upgrade and take the migration pain.

**Comment by thomas-fossati** [comment]
> The point is that there will be a continuing stream of breaking changes over the coming months. There is no point in delaying. And I this case, the point is to force the migration early rather than allowing to proliferate.
> 
> I'm fine with tagging and doing a lib release off `main` before this is merged (ditto for equivalent changes on `corim`). However, given that the spec is in draft, there is no point in maintaining stability in lib interface if it means it will grow increasingly stale. I don't think we're at the stage of even considering /v2 - - too far into the future. We should not allow this to fester foe months. And the crypto key changes will improve robustness of generated corims, and relying services, making things easier in the mean time. As those are already gonna break templates, additional disruption from this is marginal.
> 
> Besides, dependants are pinned to a particular tag/commit so it's not like they suddenly gonna break when this is merged - - they can choose when they want to upgrade and take the migration pain.

I'd rather take the reciprocal route, i.e., rather than merging this to main we start a dev/next branch which will eventually become v2 where we pack all the breaking stuff -- and we start versioning the templates too.  `veraison/corim` can start consuming this dev/next immediately.

**Comment by setrofim** [comment]
That's a bad idea. We're doubling the maintenance burden. And even with a lot of effort the two will _inevetably_ diverge -- some fixes will only end up on one or the other. If we do this, we then must also insit that all external contributors submit pull requests agains both branches (unless they are for next-only features). No. There is only one ongoing development branch. All other branches are short-term feature/demo branches destined to atrophy and die within the lifespan of a few weeks/couple of months at most.

Versioning "template" formats is definitely something we ought to be doing, and again,  as soon as possible, even if it breaks existing users. This (and argubly the hash format change) should be viewed as a design bug being fixed -- compatiblity shouldn't stand in the way way of that. Basically, the code is not mature enough at the moment to be stable.

**Comment by setrofim** [comment]
I've amended the commit to add this to `codify()`:

https://github.com/veraison/swid/pull/44/files#diff-d1549bb0639eaa3d0fbbb17e962b8612cb4e6cc02f02daa75bf72ac8fda36e99R190

This will allow for old templates to be handled correctly (any new JSON will be written with ";" as the separator. So this specific change will no longer break templates.  (They will still be broken by the crypto key change, but is orthogonal to this pull).

However, the wider point stands -- IMO it is a mistake to avoid breaking changes at this stage, if it means making things more usable, better aligned with the wider world, or more up to day with the current state of the draft spec. Expecially given tiny number of current dependents (13 packages, most of which are in fact maintained by us anyway). To be clear, I'm not suggesting we should break things willly-nilly, each break should be deliberate. But we should not shy away from it if makes the code better in the long term, even if it means the pane of adapting exting user code in the short term.

**Comment by thomas-fossati** [comment]
> I've amended the commit to add this to `codify()`:
> 
> https://github.com/veraison/swid/pull/44/files#diff-d1549bb0639eaa3d0fbbb17e962b8612cb4e6cc02f02daa75bf72ac8fda36e99R190
> 
> This will allow for old templates to be handled correctly (any new JSON will be written with ";" as the separator. So this specific change will no longer break templates. (They will still be broken by the crypto key change, but is orthogonal to this pull).

good stuff

**Comment by thomas-fossati** [comment]
> That's a bad idea. We're doubling the maintenance burden. And even with a lot of effort the two will _inevetably_ diverge -- some fixes will only end up on one or the other. If we do this, we then must also insit that all external contributors submit pull requests agains both branches (unless they are for next-only features). No. There is only one ongoing development branch. All other branches are short-term feature/demo branches destined to atrophy and die within the lifespan of a few weeks/couple of months at most.
> 
> Versioning "template" formats is definitely something we ought to be doing, and again, as soon as possible, even if it breaks existing users.

adding explicit versioning is not going to be a breaking change, as long as absence of version indicator is implicitly given a fixed name (e.g., v0).

> This (and argubly the hash format change) should be viewed as a design bug being fixed -- compatiblity shouldn't stand in the way way of that. Basically, the code is not mature enough at the moment to be stable.

Note that we advertise v1 already to our users (https://github.com/veraison/swid/releases/tag/v1.1.0) which comes with a number of promises -- why we jumped the gun is not completely clear but there we are.

**Comment by setrofim** [comment]
> Note that we advertise v1 already to our users (https://github.com/veraison/swid/releases/tag/v1.1.0) which comes with a number of promises

I mean, this is just a semver version. In theory, it doesn't mean anything except in relation to the pervious versions (i.e. that it make a breaking change from v0.X.Y). In themselves, semver versions do not imply anything about maturity or stability.

**Comment by thomas-fossati** [comment]
> > Note that we advertise v1 already to our users (https://github.com/veraison/swid/releases/tag/v1.1.0) which comes with a number of promises
> 
> I mean, this is just a semver version. In theory, it doesn't mean anything except in relation to the pervious versions (i.e. that it make a breaking change from v0.X.Y). In themselves, semver versions do not imply anything about maturity or stability.

Not really.  In the go world v1 is the first stable version, see https://go.dev/doc/modules/release-workflow

**Comment by setrofim** [comment]
> Not really. In the go world v1 is the first stable version, see https://go.dev/doc/modules/release-workflow

OK, well, in that case, this codeline isn't at v1, no matter what the release tag says. It's simply not mature enough for stability. 

Right, ok, in light of that, revised proposal:

- We do what you suggested but in reverse -- `main` (i.e. active development) is now in v2, there is a `legacy` v1 branch off the last v1.X.Y tag.
- We do everything v2, and effectively ignore v1. If (and _only_ if) somone specifically asks for particular fixes to be backported to v1 we do that on the `legacy` branch, and make a new v1.X.Y  release as necessary.
- We do _not_ make an official v2 release at least until the CORIM spec (and/or any other pertient spec) is published. Every actual release we do officially becomes a "release candidate"; i.e., insteand of doing a v2.0.0, we do a v2.0.0rc0; instead of following that up with a v2.0.1 or v.2.1.0 or v3.0.0 (as would be required by semver convetion), we do a v2.0.0rc1, and essentally keep incrementing the release candidate value instend of the release number.

It's a bit hacky -- we basically lose semver until v2.0.0 can be published (but not a big deal since we're not ready of stability anyway, so the distinctions between major, minor and patch are not important atm). However, this allows us, to (a) adhere to the Golang verisioning convetion, while (b) continuing to develop the codeline as imature and unstable (which it actually is), and (c) not have to actively maintain two ongoing development branches (I'm willing to bet that hardly anyone would actually ask us to backport fixes to v1 rather than migrating their code to v2 when asked).

**Comment by thomas-fossati** [comment]
> > Not really. In the go world v1 is the first stable version, see https://go.dev/doc/modules/release-workflow
> 
> OK, well, in that case, this codeline isn't at v1, no matter what the release tag says. It's simply not mature enough for stability.

If the remark is about `veraison/corim` I fully agree (the prerequisites aren't there: the spec is still in flux), but one could debate about `veraison/swid` which is based on stable specs (an exiting ISO standard, and a published RFC.).  Personally I wouldn't have tagged `veraison/swid` v1 but that's another conversation.  BTW, we could still `retract`, this kind of things happen and the language takes care of such situations...

> Right, ok, in light of that, revised proposal:
> 
> * We do what you suggested but in reverse -- `main` (i.e. active development) is now in v2, there is a `legacy` v1 branch off the last v1.X.Y tag.

I don't understand why v2 can't be worked on on a long lived dev branch.  Maybe we should have a chat?

**Comment by setrofim** [comment]
> BTW, we could still retract, this kind of things happen and the language takes care of such situations...

Retract

> I don't understand why v2 can't be worked on on a long lived dev branch. Maybe we should have a chat?

It could in principle it's just a lot more work  and is begging for problems down the line (when it gets out sync with `main`). And besides -- we don't want new people starting to use the old version  in the mean time.

Happy to have a chat. Erm, how do we do it while Slack is (hopefully temporarily) not an option. Zoom?

**Review by thomas-fossati — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
